
require("./ExpenseReportForm.module.css");
const styles = {
  expenseReportForm: 'expenseReportForm_6ec9b15d',
  header: 'header_6ec9b15d',
  logo: 'logo_6ec9b15d',
  formInfo: 'formInfo_6ec9b15d',
  formGroup: 'formGroup_6ec9b15d',
  userDropdown: 'userDropdown_6ec9b15d',
  sectionTitle: 'sectionTitle_6ec9b15d',
  expenseTable: 'expenseTable_6ec9b15d',
  deleteBtn: 'deleteBtn_6ec9b15d',
  totalRow: 'totalRow_6ec9b15d',
  addBtn: 'addBtn_6ec9b15d',
  attachmentsSection: 'attachmentsSection_6ec9b15d',
  attachmentsList: 'attachmentsList_6ec9b15d',
  attachmentItem: 'attachmentItem_6ec9b15d',
  removeAttachment: 'removeAttachment_6ec9b15d',
  summarySection: 'summarySection_6ec9b15d',
  summaryItem: 'summaryItem_6ec9b15d',
  summaryLabel: 'summaryLabel_6ec9b15d',
  summaryValue: 'summaryValue_6ec9b15d',
  summaryTotal: 'summaryTotal_6ec9b15d',
  printOnly: 'printOnly_6ec9b15d',
  signatureSection: 'signatureSection_6ec9b15d',
  signatureBox: 'signatureBox_6ec9b15d',
  signatureImage: 'signatureImage_6ec9b15d',
  signatureCanvas: 'signatureCanvas_6ec9b15d',
  clearSignatureBtn: 'clearSignatureBtn_6ec9b15d',
  signatureLine: 'signatureLine_6ec9b15d',
  actions: 'actions_6ec9b15d',
  saveBtn: 'saveBtn_6ec9b15d',
  submitBtn: 'submitBtn_6ec9b15d',
  printBtn: 'printBtn_6ec9b15d',
  statusBar: 'statusBar_6ec9b15d',
  success: 'success_6ec9b15d',
  error: 'error_6ec9b15d',
  loadingOverlay: 'loadingOverlay_6ec9b15d',
  myReportsList: 'myReportsList_6ec9b15d',
  reportItem: 'reportItem_6ec9b15d',
  reportDate: 'reportDate_6ec9b15d',
  reportTotal: 'reportTotal_6ec9b15d',
  reportStatus: 'reportStatus_6ec9b15d',
  draft: 'draft_6ec9b15d',
  submitted: 'submitted_6ec9b15d',
  pagination: 'pagination_6ec9b15d',
  newReportBtn: 'newReportBtn_6ec9b15d'
};

export default styles;
